version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:quang@localhost:5432/person
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=quang
      - POSTGRES_DB=person
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: