name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # TODO build, test and deploy project

      # - name: Deploy to Render
      #   run: |
      #     curl --request POST \
      #         --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
      #         --header 'authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
      #         --header 'content-type: application/json'

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Use your secret Render API Key
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}  # Use your secret Service ID
        run: |
          echo "Triggering Render Deployment..."
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json"

      
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'