name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: 3.10

      - name: Create virtual environment
        run:
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Python
        run: python app.py

      # TODO build, test and deploy project

      - name: Deploy to Render
        run: |
          curl --request POST \
              --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
              --header 'authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
              --header 'content-type: application/json'
      
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'