name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # TODO build, test and deploy project

      # - name: Deploy to Render
      #   run: |
      #     curl --request POST \
      #         --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
      #         --header 'authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
      #         --header 'content-type: application/json'

      - name: Deploy to production
        uses: vuquang142k/render-deploy-action@v0.0.8
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true

      
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'