name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TODO build, test and deploy project
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: 8.0.x
      
      - name: Build
        run: dotnet restore "Person/Person/Person.csproj"

      - name: Publish
        run: dotnet publish "Person/Person/Person.csproj" -c Release -o publish --no-restore
      
      - name: Test
        run: dotnet test "Person/PersonTests/PersonTests.csproj" --no-restore

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results
          path: TestResults
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      
      - name: Deploy project
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ccf28ef5-f283-40a6-9ee9-8a2eb6fbacf4
          heroku_app_name: people-lab1
          heroku_email: 15platosha@gmail.com
          usedocker: true

      - name: Timeout
        run: sleep 20s
        shell: bash
        
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"